# Generated by Django 4.1.7 on 2023-06-06 08:56

import django.core.validators
from django.db import migrations, models
import quiz.main_page.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(6)])),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('profile_image', models.ImageField(upload_to='', validators=[quiz.main_page.validators.validate_file_size])),
            ],
        ),
    ]
