# Generated by Django 4.1.7 on 2023-07-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizuser',
            name='password',
            field=models.CharField(default='somepass', max_length=200),
        ),
    ]
